In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow_datasets as tfds
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.applications import VGG16
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import layers, models, regularizers

In [2]:
ds = fetch_ucirepo(id=360)

In [3]:
df = ds.data.features.copy()
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [4]:
target = df["CO(GT)"]
# drop the target colmn and dat and time columns
features = df.drop(columns=["CO(GT)","Date", "Time"])

In [5]:
features.replace(-200, np.nan, inplace=True)  # Nan here are -200 so replcae them with np.nan
#features.fillna(features.mean(), inplace=True)  # fill the nan with mean of each column
features.fillna(features.mean(), inplace=True)  # fill the nan with mean of each column

In [6]:
target.replace(-200, np.nan, inplace=True)  # Nan here are -200 so replcae them with np.nan
#features.fillna(features.mean(), inplace=True)  # fill the nan with mean of each column
target.fillna(target.mean(), inplace=True)  # fill the nan with mean of each column

In [7]:
features.head()

,PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [8]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [9]:
# Scaling data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
# Sequential: Input > Hidden Layer 1 > Hidden Layer 2 > Output
baseline_model = tf.keras.Sequential([
    tf.keras.Input(shape=(X_train_scaled.shape[1],)), # input layer with shape matching the number of features
    layers.Dense(128, activation="relu"),  # first hidden layer with 128 neurons and relu activation function
    layers.Dense(64, activation="relu"), # second hidden layer with 64 neurons and relu activation function
    layers.Dense(32, activation="relu"), # third hidden layer with 32 neurons and relu activation function
    layers.Dense(1) # output layer with 1 neuron - no activation function cause its regression (continuous output)
])

baseline_model.compile(
    optimizer="adam",   # Controls how weights are updated
    loss="mse", # what the model tries to minimize
    metrics=["mae"] # MAE (Mean Absolute Error) what we monitor, not optimize
)

baseline_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 128)            │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,033 (47.00 KB)

 Trainable params: 12,033 (47.00 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
history_baseline = baseline_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

Epoch 1/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2487 - mae: 0.3305 - val_loss: 0.2786 - val_mae: 0.3586
Epoch 2/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2329 - mae: 0.3246 - val_loss: 0.2770 - val_mae: 0.3630
Epoch 3/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2277 - mae: 0.3193 - val_loss: 0.2647 - val_mae: 0.3466
Epoch 4/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2150 - mae: 0.3133 - val_loss: 0.2629 - val_mae: 0.3484
Epoch 5/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2392 - mae: 0.3322 - val_loss: 0.2642 - val_mae: 0.3452
Epoch 6/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2258 - mae: 0.3244 - val_loss: 0.2597 - val_mae: 0.3410
Epoch 7/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2245 - mae: 0.3223 - val_loss: 0.2641 - val_mae: 0.3482
Epoch 8/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2252 - mae: 0.3187 - val_loss: 0.2708 - val_mae: 0.3527
Epoch 9/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2302 - mae: 0.3209 - val_loss: 0.2779 - val_mae: 0.3671
Epoch 10/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2413 - mae: 0.3273 - val_loss: 0.2719 - val_mae: 0.3547
Epoch 11/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2148 - mae: 0.3145 - val_loss: 0.2596 - val_mae: 0.3396
Epoch 12/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2209 - mae: 0.3145 - val_loss: 0.2671 - val_mae: 0.3545
Epoch 13/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2190 - mae: 0.3160 - val_loss: 0.2618 - val_mae: 0.3443
Epoch 14/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2177 - mae: 0.3127 - val_loss: 0.2733 - val_mae: 0.3529
Epoch 15/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2134 - mae: 0.3103 - val_loss: 0.2838 - val_mae: 0.3622
Epoch 16/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2095 - mae: 0.3071 - val_loss: 0.2557 - val_mae: 0.3471
Epoch 17/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1945 - mae: 0.2974 - val_loss: 0.2545 - val_mae: 0.3456
Epoch 18/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1965 - mae: 0.3012 - val_loss: 0.2612 - val_mae: 0.3416
Epoch 19/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2114 - mae: 0.3041 - val_loss: 0.2497 - val_mae: 0.3371
Epoch 20/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1871 - mae: 0.2901 - val_loss: 0.2593 - val_mae: 0.3471

In [24]:
reg_model = tf.keras.Sequential([
    tf.keras.Input(shape=(X_train_scaled.shape[1],)),  # input layer
    layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(0.0001)),
    layers.Dropout(0.2),  # Drop 30% of neurons
    layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(0.0001)),
    layers.Dropout(0.2),
    layers.Dense(32, activation="relu", kernel_regularizer=regularizers.l2(0.0001)),
    layers.Dropout(0.2),
    layers.Dense(1)
])

reg_model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

reg_model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                │ (None, 128)            │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,033 (47.00 KB)

 Trainable params: 12,033 (47.00 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
history_reg = reg_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

Epoch 1/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 2.0090 - mae: 1.0519 - val_loss: 0.4594 - val_mae: 0.4969
Epoch 2/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.7175 - mae: 0.5978 - val_loss: 0.3472 - val_mae: 0.4037
Epoch 3/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.5570 - mae: 0.5306 - val_loss: 0.3938 - val_mae: 0.4385
Epoch 4/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5170 - mae: 0.5050 - val_loss: 0.3767 - val_mae: 0.4297
Epoch 5/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5534 - mae: 0.5172 - val_loss: 0.3369 - val_mae: 0.4030
Epoch 6/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4746 - mae: 0.4891 - val_loss: 0.4285 - val_mae: 0.4619
Epoch 7/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4719 - mae: 0.4826 - val_loss: 0.3425 - val_mae: 0.4053
Epoch 8/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4335 - mae: 0.4637 - val_loss: 0.3350 - val_mae: 0.3897
Epoch 9/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4577 - mae: 0.4698 - val_loss: 0.3285 - val_mae: 0.3926
Epoch 10/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4421 - mae: 0.4647 - val_loss: 0.3150 - val_mae: 0.3843
Epoch 11/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4260 - mae: 0.4513 - val_loss: 0.3059 - val_mae: 0.3773
Epoch 12/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4204 - mae: 0.4534 - val_loss: 0.3200 - val_mae: 0.3776
Epoch 13/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3946 - mae: 0.4353 - val_loss: 0.3171 - val_mae: 0.3851
Epoch 14/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4015 - mae: 0.4351 - val_loss: 0.2990 - val_mae: 0.3713
Epoch 15/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3949 - mae: 0.4391 - val_loss: 0.3710 - val_mae: 0.4214
Epoch 16/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4100 - mae: 0.4272 - val_loss: 0.3346 - val_mae: 0.4003
Epoch 17/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3866 - mae: 0.4338 - val_loss: 0.3042 - val_mae: 0.3762
Epoch 18/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3738 - mae: 0.4240 - val_loss: 0.3042 - val_mae: 0.3727
Epoch 19/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3986 - mae: 0.4328 - val_loss: 0.3236 - val_mae: 0.3899
Epoch 20/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3969 - mae: 0.4323 - val_loss: 0.3359 - val_mae: 0.4077

In [26]:
from tensorflow.keras import callbacks
# callbacks to save the best model and stop early if no improvement

checkpoint_cb = callbacks.ModelCheckpoint(
    "best_model.keras",
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

earlystop_cb = callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

In [27]:
# train regularized model with callbacks
history_reg_cb = reg_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    callbacks=[checkpoint_cb, earlystop_cb],
    verbose=1
)

Epoch 1/20
183/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3832 - mae: 0.4188
Epoch 1: val_loss improved from inf to 0.29455, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3833 - mae: 0.4189 - val_loss: 0.2945 - val_mae: 0.3724
Epoch 2/20
176/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3992 - mae: 0.4293
Epoch 2: val_loss improved from 0.29455 to 0.29347, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3973 - mae: 0.4285 - val_loss: 0.2935 - val_mae: 0.3679
Epoch 3/20
184/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3628 - mae: 0.4132
Epoch 3: val_loss improved from 0.29347 to 0.28972, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3627 - mae: 0.4132 - val_loss: 0.2897 - val_mae: 0.3623
Epoch 4/20
184/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3858 - mae: 0.4133
Epoch 4: val_loss did not improve from 0.28972
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3858 - mae: 0.4135 - val_loss: 0.3130 - val_mae: 0.3889
Epoch 5/20
177/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3270 - mae: 0.3949
Epoch 5: val_loss did not improve from 0.28972
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3285 - mae: 0.3952 - val_loss: 0.3087 - val_mae: 0.3819
Epoch 6/20
178/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3444 - mae: 0.3991
Epoch 6: val_loss did not improve from 0.28972
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3449 - mae: 0.3995 - val_loss: 0.3680 - val_mae: 0.4212
Epoch 7/20
169/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4005 - mae: 0.4228
Epoch 7: val_loss improved from 0.28972 to 0.28910, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3978 - mae: 0.4217 - val_loss: 0.2891 - val_mae: 0.3683
Epoch 8/20
172/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3569 - mae: 0.4122
Epoch 8: val_loss did not improve from 0.28910
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3567 - mae: 0.4117 - val_loss: 0.2978 - val_mae: 0.3745
Epoch 9/20
180/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3432 - mae: 0.4003
Epoch 9: val_loss did not improve from 0.28910
188/188 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3439 - mae: 0.4005 - val_loss: 0.2957 - val_mae: 0.3669
Epoch 10/20
182/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3436 - mae: 0.3966
Epoch 10: val_loss did not improve from 0.28910
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3440 - mae: 0.3969 - val_loss: 0.3275 - val_mae: 0.3936
Epoch 11/20
168/188 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3537 - mae: 0.4067
Epoch 11: val_loss did not improve from 0.28910
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3544 - mae: 0.4065 - val_loss: 0.3307 - val_mae: 0.3958
Epoch 12/20
173/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3631 - mae: 0.4068
Epoch 12: val_loss improved from 0.28910 to 0.28872, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3618 - mae: 0.4063 - val_loss: 0.2887 - val_mae: 0.3632
Epoch 13/20
187/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3774 - mae: 0.4066
Epoch 13: val_loss did not improve from 0.28872
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3772 - mae: 0.4066 - val_loss: 0.2888 - val_mae: 0.3682
Epoch 14/20
174/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3407 - mae: 0.3943
Epoch 14: val_loss did not improve from 0.28872
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3400 - mae: 0.3941 - val_loss: 0.2987 - val_mae: 0.3788
Epoch 15/20
172/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3384 - mae: 0.4047
Epoch 15: val_loss did not improve from 0.28872
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3384 - mae: 0.4040 - val_loss: 0.2976 - val_mae: 0.3736
Epoch 16/20
171/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3493 - mae: 0.3944
Epoch 16: val_loss improved from 0.28872 to 0.28872, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3491 - mae: 0.3949 - val_loss: 0.2887 - val_mae: 0.3721
Epoch 17/20
175/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3623 - mae: 0.4069
Epoch 17: val_loss did not improve from 0.28872
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3605 - mae: 0.4059 - val_loss: 0.2973 - val_mae: 0.3808
Epoch 18/20
176/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3290 - mae: 0.3954
Epoch 18: val_loss improved from 0.28872 to 0.28819, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3296 - mae: 0.3954 - val_loss: 0.2882 - val_mae: 0.3689
Epoch 19/20
172/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3313 - mae: 0.3898
Epoch 19: val_loss did not improve from 0.28819
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3311 - mae: 0.3897 - val_loss: 0.2884 - val_mae: 0.3712
Epoch 20/20
188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3258 - mae: 0.3834
Epoch 20: val_loss improved from 0.28819 to 0.28671, saving model to best_model.keras
188/188 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3259 - mae: 0.3834 - val_loss: 0.2867 - val_mae: 0.3710

In [28]:
# evaluate both models
baseline_loss, baseline_mae = baseline_model.evaluate(X_test_scaled, y_test, verbose=0)
reg_loss, reg_mae = reg_model.evaluate(X_test_scaled, y_test, verbose=0)

print(f"Baseline Model - Test Loss: {baseline_loss:.4f}, Test MAE: {baseline_mae:.4f}")
print(f"Regularized Model - Test Loss: {reg_loss:.4f}, Test MAE: {reg_mae:.4f}")

Baseline Model - Test Loss: 0.2419, Test MAE: 0.3254
Regularized Model - Test Loss: 0.2609, Test MAE: 0.3456